name: CI

on:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  test:
    runs-on: ubuntu-latest
    needs: generate

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@v5
        env:
          STACK_YAML: ${{ matrix.stack-yaml }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: rwe/actions-hlint-setup@v1
      - uses: rwe/actions-hlint-run@v2
        with:
          fail-on: warning

  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: stack-nightly.yaml
      - uses: freckle/stack-action@v5
        env:
          STACK_YAML: stack-nightly.yaml
        with:
          stack-arguments: --resolver nightly
